title: LiveDataTrentino
greeting: LiveData Trentino Catalog
description: The LiveData Trentino catalog collects and shares datasets about the Trentino region (autonomous province of Trentino, Italy). The catalog provides data about the Trentino geography, as well as data about Trentino's society, like transportation, points of interest, facilities, and others. The LiveData Trentino catalog is part of the DataScientia Open Data Space. The data shared by the catalog are compliant with the quality criteria defined by DataScientia, moreover they are highly reusable and composable with other data produced following the DataScientia guidelines (more in detail, adopting the iTelos methodology).
baseurl: /LiveDataTrentino
logo: /img/LD-trentino.png

# Site theme
jkan_theme: Default

# Authentication
github_client_id: cf9cb57bdb65a549387f
gatekeeper_host: http://localhost:9999

# Dataset schema
schema: default

# Nav bar
navigation:
  - title: About Us
    url: http://datascientia.disi.unitn.it/
  - title: Datasets
    url: /datasets/
  - title: Organizations
    url: /organizations/
  - title: Services
    url: /#services
  - title: FAQ
    url: /faq/

# Collections
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  organizations:
    output: true
    permalink: /organizations/:path/

# Collections (cont'd)
defaults:
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      organization: N/A
  - scope:
      path: ""
      type: organizations
    values:
      layout: organization

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Google Analytics
google_analytics:
  enabled: false
  code: "UA-XXXXXX-1"

# US Digital Analytics Program - https://analytics.usa.gov
digital_analytics_program:
  enabled: false
  agency: ""
  subagency: ""

# Hypothesis.io - Annotator
hypothesis:
  enabled: false

# Twitter
twittercard:
  enabled: false
  username: "@"

# Open Graph
opengraph:
  enabled: true

# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - node_modules
  - scripts/src
  - package.json
  - webpack.config.js
  - README.md
  - LICENSE
